version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: php ./roadrunner/workers/queue.php
  relay: pipes

amqp:
  addr: amqp://guest:guest@rabbitmq:5672

jobs:
  num_pollers: 64
  timeout: 60
  pipeline_size: 100000

  pool:
    num_workers: 10
    allocate_timeout: 60s
    destroy_timeout: 60s

  consume: [ "profile-information" ]

  pipelines:
    profile-information:
      driver: amqp
      queue: profile-information
      config:
        redial_timeout: 60
        queue: profile-information
        exchange_type: direct
        routing_key: profile-information
        multiple_ack: false
        requeue_on_fail: true
        queue_auto_delete: false
        exchange_auto_delete: false
