<?php

declare(strict_types=1);

define('ELASTICSEARCH_HOSTS', ['GLCI_ELASTICSEARCH_HOST']);
define('ELASTICSEARCH_USERNAME', 'GLCI_ELASTICSEARCH_USERNAME');
define('ELASTICSEARCH_PASSWORD', 'GLCI_ELASTICSEARCH_PASSWORD');
