<?php

declare(strict_types=1);

define('DB_DRIVER', 'pdo_mysql');
define('DB_HOST', 'GLCI_PROFILE_INFORMATION_DB_HOST');
define('DB_PORT', 3306);
define('DB_USER', 'GLCI_PROFILE_INFORMATION_DB_USER');
define('DB_PASSWORD', 'GLCI_PROFILE_INFORMATION_DB_PASSWORD');
define('DB_NAME', 'GLCI_PROFILE_INFORMATION_DB_NAME');

define('PROFILE_INFORMATION_QUEUE_NAME', 'GLCI_PROFILE_INFORMATION_QUEUE_NAME');
