<?php

declare(strict_types=1);

define('DB_DRIVER', 'pdo_mysql');
define('DB_HOST', 'GLCI_SEARCH_DB_HOST');
define('DB_PORT', 3306);
define('DB_USER', 'GLCI_SEARCH_DB_USER');
define('DB_PASSWORD', 'GLCI_SEARCH_DB_PASSWORD');
define('DB_NAME', 'GLCI_SEARCH_DB_NAME');

define('ELASTICSEARCH_HOSTS', ['GLCI_ELASTICSEARCH_HOST']);
define('ELASTICSEARCH_USERNAME', 'GLCI_ELASTICSEARCH_USERNAME');
define('ELASTICSEARCH_PASSWORD', 'GLCI_ELASTICSEARCH_PASSWORD');
